### ISSUE TITLE
Elasticsearch package interface

### ISSUE THREAD

**Issue by PumpkinSeed** [tothmate90/news-scraper#2]
You should create an [interface](https://gobyexample.com/interfaces) type for the elasticsearch package.

```
type Handler interface {
  Create() error
  GetAll(from, size int) (*elastic.SearchResult, error)
  ...
}
```

`type Handler struct` should be `type handler struct` and the `New(...)` function returns the interface. If you have any struct field what you want to use from outside of the package write getter/setter methods and add them to the Handler interface.

In the api package make sure you only call the methods implemented by the interface.

**Comment by tetff** [comment]
Issue resolved.
